ProyectoIS2/Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from proyecto.views import index_proyecto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_portal, name='portal'),
    path('inicio/', include('home.urls')),
    path('logout/', views.user_logout, name='logout'), 
    path('inicio_proyecto/', index_proyecto, name='index'),
    path('proyecto/', include("proyecto.urls")),
    path('item/', include("item.urls")),
    path('usuario/', include("usuario.urls")),
    path('lineabase/', include("lineab.urls")), 
]

ProyectoIS2/Proyecto/home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns=[
	path('', views.index_portal, name='index'),
    path('',views.user_logout,name='logout'),
    path('ingresar/',views.user_login,name='user_login'),
  
]

ProyectoIS2/Proyecto/item/urls.py
from django.urls import path
from item.views import ItemCreate, ItemList, ItemUpdate, ItemDelete, item_list_total
app_name = 'item'

urlpatterns = [
    path("registrar/", ItemCreate.as_view(), name="registrar_item"),
    path("listar/<int:id>", ItemList.as_view(), name="listar_item"),   
    path('listaDeItem/', item_list_total, name= 'lista_total'),
    path("editar/<int:pk>", ItemUpdate.as_view(), name="editar_item"),   
    path("eliminar/<int:pk>", ItemDelete.as_view(), name="eliminar_item"),   

]

ProyectoIS2/Proyecto/lineab/urls.py
from django.urls import path
from lineab.views import LineaCreate, LineaList, LineaUpdate, LineaDelete, linea_list_total
app_name = 'lineab'

urlpatterns = [
    path("registrar/", LineaCreate.as_view(), name="registrar_linea"),
    path("listar/<int:id>", LineaList.as_view(), name="listar_linea"),   
    path('listaDeLineas/', linea_list_total, name= 'lista_total'),
    path("editar/<int:pk>", LineaUpdate.as_view(), name="editar_linea"),   
    path("eliminar/<int:pk>", LineaDelete.as_view(), name="eliminar_linea"),   

]

ProyectoIS2/Proyecto/proyecto/urls.py
from django.urls import path
from proyecto.views import index_proyecto, ProyectoCreate, ProyectoList, ProyectoUpdate, ProyectoDelete, proyecto_list_total

app_name = 'proyecto'

urlpatterns = [
    path("", index_proyecto, name="index_proyecto"),
    path("registrar/", ProyectoCreate.as_view(), name="registrar_proyecto"),
    path("listar/<int:id>", ProyectoList.as_view(), name="proyecto_listar"),
    path('listaDeProyecto/', proyecto_list_total, name= 'lista_total'),
    path("editar/<int:pk>", ProyectoUpdate.as_view(), name="editar_proyecto"),
    path("eliminar/<int:pk>", ProyectoDelete.as_view(), name="eliminar_proyecto"),
]

ProyectoIS2/Proyecto/usuario/urls.py
from django.urls import path
from usuario.views import index_usuario, UsuarioCreate, UsuarioList,UsuarioUpdate,UsuarioDelete

app_name = 'usuario'

urlpatterns = [
    path("", index_usuario, name="index_usuario"),
    path("registrar/", UsuarioCreate.as_view(), name="registrar_usuario"),
    path("editar/<int:pk>", UsuarioUpdate.as_view(), name="usuario_editar"),   
    path("eliminar/<int:pk>", UsuarioDelete.as_view(), name="usuario_eliminar"),   
    path("listar/", UsuarioList.as_view(), name="listar_usuario"),
    
]

ProyectoIS2/Proyecto/templates/base/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    -->
      {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}" type="text/css">
        
    <title>{% block title %}Sistema{% endblock %}</title>
  </head>
<body>
  <div class="container">
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="{% url 'index'%}">Inicio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Usuario
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'usuario:registrar_usuario' %}">Registrar Usuario</a>
              <a class="dropdown-item" href="{% url 'usuario:listar_usuario' %}">Listar Usuarios</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Proyectos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'proyecto:registrar_proyecto' %}">Registrar Proyecto</a>
              <a class="dropdown-item" href="{% url 'proyecto:lista_total' %}">Listar Proyectos</a>
            </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Linea Base
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'lineab:registrar_linea' %}">Registrar Linea Base</a>
                <a class="dropdown-item" href="{% url 'lineab:lista_total' %}">Listar Linea Base</a>
        
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Item
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'item:registrar_item' %}">Registrar Item</a>
                 <a class="dropdown-item" href="{% url 'item:lista_total' %}">Listar Item</a>
              </div>
            </li>
        </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Opciones
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="http://127.0.0.1:8000/admin/login/?next=/admin/">Administrador del Sistema</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
            
              </div>
            </li>
        
            </ul>
      </div>
    </nav>
    {% endblock%}
    
    {% block content %}
    <div class="container"> 
      <div class="jumbotron">
        <div class='Bienvenido'>Bienvenido a la aplicación!</div>   
        <h6>Que le gustaria hacer?</h6>   
      </div>
    </div>
   {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>