ProyectoIS2/Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from proyecto.views import index_proyecto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_portal, name='portal'),
    path('inicio/', include('home.urls')),
    path('logout/', views.user_logout, name='logout'), 
    path('inicio_proyecto/', index_proyecto, name='index'),
    path('proyecto/', include("proyecto.urls")),
    path('item/', include("item.urls")),
    path('usuario/', include("usuario.urls")),
    path('lineabase/', include("lineab.urls")), 
]

ProyectoIS2/Proyecto/home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns=[
	path('', views.index_portal, name='index'),
    path('',views.user_logout,name='logout'),
    path('ingresar/',views.user_login,name='user_login'),
  
]

ProyectoIS2/Proyecto/lineab/urls.py
from django.urls import path
from lineab.views import LineaCreate, LineaList, LineaUpdate, LineaDelete, linea_list_total
app_name = 'lineab'

urlpatterns = [
    path("registrar/", LineaCreate.as_view(), name="registrar_linea"),
    path("listar/<int:id>", LineaList.as_view(), name="listar_linea"),   
    path('listaDeLineas/', linea_list_total, name= 'lista_total'),
    path("editar/<int:pk>", LineaUpdate.as_view(), name="editar_linea"),   
    path("eliminar/<int:pk>", LineaDelete.as_view(), name="eliminar_linea"),   

]

ProyectoIS2/Proyecto/proyecto/urls.py
from django.urls import path
from proyecto.views import index_proyecto, ProyectoCreate, ProyectoList, ProyectoUpdate, ProyectoDelete, proyecto_list_total

app_name = 'proyecto'

urlpatterns = [
    path("", index_proyecto, name="index_proyecto"),
    path("registrar/", ProyectoCreate.as_view(), name="registrar_proyecto"),
    path("listar/<int:id>", ProyectoList.as_view(), name="proyecto_listar"),
    path('listaDeProyecto/', proyecto_list_total, name= 'lista_total'),
    path("editar/<int:pk>", ProyectoUpdate.as_view(), name="editar_proyecto"),
    path("eliminar/<int:pk>", ProyectoDelete.as_view(), name="eliminar_proyecto"),
]

ProyectoIS2/Proyecto/proyecto/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Proyecto (models.Model):
	nombre = models.CharField(max_length=200)
	objetivo = models.CharField(max_length=300)
	fecha_ini = models.DateField()
	fecha_limite = models.DateField()
	cant_dias_atrasados = models.IntegerField(default=0)
	vence = 'NO'
	vence_mes = models.CharField(max_length=3, default=vence)
	ACTIVO ='ACT'
	BLOQUEADO='BLO'
	FINALIZADO='FIN'
	tipo_estado=((ACTIVO, 'Activo'),
				(BLOQUEADO, 'Bloqueado'),
				(FINALIZADO, 'Finalizado'))
	estado = models.CharField(max_length=15, choices = tipo_estado, default = ACTIVO) 
	ANALISIS = 'ANA'
	DISENHO = 'DIS'
	CODIFICACION = 'COD'
	PRUEBA = 'PRU'
	MANTENIMIENTO = 'MAN'
   
	tipo_fase = ((ANALISIS, 'Analisis'),
				(DISENHO, 'Diseño'),
				(CODIFICACION, 'Codificacion'),
				(PRUEBA, 'Prueba'),
				(MANTENIMIENTO, 'Mantenimiento'))
	fase =  models.CharField(max_length=15, choices = tipo_fase, default = ANALISIS)
	usu = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	def __str__(self):
		return self.nombre

ProyectoIS2/Proyecto/proyecto/forms.py
from django import forms

from proyecto.models import Proyecto

class ProyectoForm(forms.ModelForm):
	class Meta:
		model = Proyecto
		fields = [
			'nombre',
			'objetivo',
			'fecha_ini',
			'fecha_limite',
			'estado',
			'fase',
            'usu',
			
		]
		labels = {
			'nombre' : 'Nombre Proyecto',
			'objetivo' : 'Objetivo',
			'fecha_ini': 'Fecha Inicial',
			'fecha_limite': 'Fecha Limite',
			'estado': 'Estado',
			'fase':'Fase',
            'usu':'Usuario',
		}
		widgets = {
			'nombre' : forms.TextInput(attrs={'class':'form-control'}),
			'objetivo' : forms.TextInput(attrs={'class':'form-control'}),
			'fecha_ini' : forms.TextInput(attrs={'class':'form-control'}),
			'fecha_limite' : forms.TextInput(attrs={'class':'form-control'}),
			'estado' : forms.Select(attrs={'class':'form-control'}),
			'fase' : forms.Select(attrs={'class':'form-control'}),
            'usu' : forms.Select(attrs={'class':'form-control'}),
		}

ProyectoIS2/Proyecto/proyecto/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from proyecto.forms import ProyectoForm
from proyecto.models import Proyecto
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from datetime import datetime, timedelta, date
# Create your views here.
def index_proyecto(request):
	for proy in Proyecto.objects.exclude(fecha_limite__gt=datetime.now()):
		fecha_ahora = date.today()
		fecha_prov = fecha_ahora - proy.fecha_limite
		proy.cant_dias_atrasados = int(fecha_prov.days)
		proy.save()
	proyecto = Proyecto.objects.exclude(fecha_limite__gt=datetime.now()).order_by('id')
	
	cantidad = 0
	for proy in Proyecto.objects.all():
		if (proy.fecha_limite.day > date.today().day and proy.fecha_limite.month == date.today().month and proy.fecha_limite.year == date.today().year):
			cantidad = cantidad + 1
			proy.vence_mes ='SI'
			proy.save()
	contenido = {'proyectos':proyecto,'cantidad':cantidad}
	return render(request, 'proyecto/index.html', contenido)
'''
def registrar_proyecto(request):	
	if request.method == 'POST':
		form = ProyectoForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('proyecto:listar_proyecto')
	else:
		form = ProyectoForm()
	return render(request, 'proyecto/proyecto_form.html', {'form':form})
'''
def proyecto_list_total(request):
	proyecto = Proyecto.objects.all().order_by('id')
	contenido = {'proyectos':proyecto}
	return render(request, 'proyecto/lista_total_proyecto.html', contenido)


class ProyectoList(ListView):
	model = Proyecto
	template_name = 'proyecto/listar_proyecto.html'
	def get_queryset(self):
		return Proyecto.objects.filter(usu=self.kwargs['id']).order_by('id')

class ProyectoCreate(CreateView):
	model = Proyecto
	form_class = ProyectoForm
	template_name = 'proyecto/proyecto_form.html'
	success_url = reverse_lazy('proyecto:lista_total')	

class ProyectoUpdate(UpdateView):
	model = Proyecto
	form_class = ProyectoForm
	template_name = 'proyecto/proyecto_form.html'
	success_url = reverse_lazy('proyecto:lista_total')


class ProyectoDelete(DeleteView):
	model = Proyecto
	template_name = 'proyecto/proyecto_delete.html'
	success_url = reverse_lazy('proyecto:lista_total')	

ProyectoIS2/Proyecto/templates/proyecto/index.html
{% extends 'base/base.html' %}
{% block content %}
{% if cantidad %}
	<div class="alert alert-dismissible alert-warning">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  
	  <h4 class="alert-heading">Warning!</h4>
	  <p class="mb-0">La cantidad de proyectos a vencer este mes es {{cantidad}}, <a href="{% url 'proyecto:lista_total' %}" class="alert-link">listar proyectos</a>.</p>
	</div>
{% endif %} 
<table class="table table-hover">
  <thead>
		<tr>
			<td align="center">Nombre</td>
			<td align="center">Fecha Limite</td>
			<td align="center">Cantidad Días Atrasados</td>
			<td align="center">Acciones</td>
		</tr>		
	</thead>
	<tbody>
		{% if proyectos %}
			{% for proyecto in proyectos %}
				<tr class="table-dark">
					<td align="center">{{ proyecto.nombre }}</td>
					<td align="center">{{ proyecto.fecha_limite }}</td>
					<td align="center">{{ proyecto.cant_dias_atrasados }}</td>
					<td align="center">
						<a class="btn btn-success" href="{% url 'proyecto:editar_proyecto' proyecto.id%}">
							Editar
						</a>
						<a class="btn btn-danger" href="{% url 'proyecto:eliminar_proyecto' proyecto.id%}">
							Eliminar
						</a>
						<!--En listar proyecto se agregar listar las lineas base que tiene ese proyecto, por eso se le pasa el id del proyecto-->
						<a class="btn btn-primary" href="{% url 'lineab:listar_linea' proyecto.id%}">
							Ver Linea Base
						</a>
					</td>
				</tr>
			{% endfor %}
			<h2 align="center">Lista de Proyectos Atrasados</h2>
		{% else %}
			<h2 align="center">No hay registros de Proyectos Atrasados</h2>
		{% endif %}   
	</tbody>
</table> 

{% endblock%}

ProyectoIS2/Proyecto/templates/proyecto/lista_total_proyecto.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-hover">
	<thead>
		<tr>
			<td align="center">N°</td>
			<td align="center">Nombre</td>
			<td align="center">Objetivo</td>
			<td align="center">Fecha Inicio</td>
			<td align="center">Fecha Limite</td>
			<td align="center">Estado</td>
			<td align="center">Fase</td>
			<td align="center">Vence este mes</td>
			<td align="center">Usuario</td>
			<td align="center" >Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if proyectos %}
		{% for proyecto in proyectos %}
		<tr class="table-dark">
			<td align="center">{{ proyecto.id }}</td>
			<td align="center">{{ proyecto.nombre }}</td>
			<td align="center">{{ proyecto.objetivo }}</td>
			<td align="center">{{ proyecto.fecha_ini }}</td>
			<td align="center">{{ proyecto.fecha_limite }}</td>
			<td align="center">{{ proyecto.estado }}</td> 
			<td align="center">{{ proyecto.fase}}</td>
			<td align="center">{{ proyecto.vence_mes}}</td>
			<td align="center">{{ proyecto.usu.username}}</td>
			<td align="center">
				<a class="btn btn-primary" href="{% url 'proyecto:editar_proyecto' proyecto.id  %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'proyecto:eliminar_proyecto' proyecto.id  %}">Eliminar</a>
                <!--En listar proyecto se agregar listar las lineas base que tiene ese proyecto, por eso se le pasa el id del proyecto-->
				<a class="btn btn-success" href="{% url 'lineab:listar_linea' proyecto.id %}">Ver Linea Base</a>
			</td>
		</tr>
		{% endfor %}
		<h2 align="center">Lista de Proyectos</h2>
		{% else %}
		<h2 align="center">No hay registros de Proyectos</h2>
		{% endif %}
	</tbody>
</table> 
<h><a class="btn btn-success" href="{% url 'proyecto:index_proyecto' %}">Volver</a></h>

{% endblock%}

ProyectoIS2/Proyecto/templates/proyecto/listar_proyecto.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-hover">
	<thead>
		<tr>
			<td align="center">N°</td>
			<td align="center">Nombre</td>
			<td align="center">Objetivo</td>
			<td align="center">Fecha Inicio</td>
			<td align="center">Fecha Limite</td>
			<td align="center">Estado</td>
			<td align="center">Fase</td>
			<td align="center">Vence este mes</td>
			<td align="center">Usuario</td>
			<td align="center" >Acciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
			{% for proyecto in object_list %}
				<tr class="table-dark">
					<td align="center">{{ proyecto.id }}</td>
					<td align="center">{{ proyecto.nombre }}</td>
					<td align="center">{{ proyecto.objetivo }}</td>
					<td align="center">{{ proyecto.fecha_ini }}</td>
					<td align="center">{{ proyecto.fecha_limite }}</td>
					<td align="center">{{ proyecto.estado }}</td> 
					<td align="center">{{ proyecto.fase}}</td>
					<td align="center">{{ proyecto.vence_mes}}</td>
					<td align="center">{{ proyecto.usu.username}}</td>
					<td align="center">
						<a class="btn btn-primary" href="{% url 'proyecto:editar_proyecto' proyecto.id%}">Editar</a>
						<a class="btn btn-danger" href="{% url 'proyecto:eliminar_proyecto' proyecto.id  %}">Eliminar</a>
						<!--En listar proyecto se agregar listar las lineas base que tiene ese proyecto, por eso se le pasa el id del proyecto-->
						<a class="btn btn-success" href="{% url 'lineab:listar_linea' proyecto.id%}">Ver Linea Base</a>
					</td>
				</tr>
			{% endfor %}
			<h2 align="center">Lista de Proyectos</h2>
		{% else %}
			<h2 align="center">No hay registros de Proyectos</h2>
		{% endif %}
	</tbody>
</table> 
<h><a class="btn btn-success" href="{% url 'proyecto:index_proyecto'%}">Volver</a></h>

{% endblock%}

ProyectoIS2/Proyecto/templates/proyecto/proyecto_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el proyecto {{ object.nombre }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-success" href="{% url 'proyecto:lista_total' %}">Cancelar</a>
</form>
{% endblock %}

ProyectoIS2/Proyecto/templates/proyecto/proyecto_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
</form>
{% endblock %}