ProyectoIS2/Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from proyecto.views import index_proyecto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_portal, name='portal'),
    path('inicio/', include('home.urls')),
    path('logout/', views.user_logout, name='logout'), 
    path('inicio_proyecto/', index_proyecto, name='index'),
    path('proyecto/', include("proyecto.urls")),
    path('item/', include("item.urls")),
    path('usuario/', include("usuario.urls")),
    path('lineabase/', include("lineab.urls")), 
]

ProyectoIS2/Proyecto/home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns=[
	path('', views.index_portal, name='index'),
    path('',views.user_logout,name='logout'),
    path('ingresar/',views.user_login,name='user_login'),
  
]

ProyectoIS2/Proyecto/proyecto/urls.py
from django.urls import path
from proyecto.views import index_proyecto, ProyectoCreate, ProyectoList, ProyectoUpdate, ProyectoDelete, proyecto_list_total

app_name = 'proyecto'

urlpatterns = [
    path("", index_proyecto, name="index_proyecto"),
    path("registrar/", ProyectoCreate.as_view(), name="registrar_proyecto"),
    path("listar/<int:id>", ProyectoList.as_view(), name="proyecto_listar"),
    path('listaDeProyecto/', proyecto_list_total, name= 'lista_total'),
    path("editar/<int:pk>", ProyectoUpdate.as_view(), name="editar_proyecto"),
    path("eliminar/<int:pk>", ProyectoDelete.as_view(), name="eliminar_proyecto"),
]

ProyectoIS2/Proyecto/usuario/urls.py
from django.urls import path
from usuario.views import index_usuario, UsuarioCreate, UsuarioList,UsuarioUpdate,UsuarioDelete

app_name = 'usuario'

urlpatterns = [
    path("", index_usuario, name="index_usuario"),
    path("registrar/", UsuarioCreate.as_view(), name="registrar_usuario"),
    path("editar/<int:pk>", UsuarioUpdate.as_view(), name="usuario_editar"),   
    path("eliminar/<int:pk>", UsuarioDelete.as_view(), name="usuario_eliminar"),   
    path("listar/", UsuarioList.as_view(), name="listar_usuario"),
    
]

ProyectoIS2/Proyecto/usuario/models.py
from django.db import models
from proyecto.models import Proyecto
from django.contrib.auth.models import User
# Create your models here.

class Usuario(models.Model):
	usuario = models.OneToOneField(User,on_delete=models.CASCADE)
	#perfil_redes = models.URLField(blank=True)
	proyecto = models.ForeignKey(Proyecto, null=True, blank=True, on_delete=models.CASCADE)
	def __str__(self):
  		return self.usuario.username

ProyectoIS2/Proyecto/usuario/forms.py
from django import forms
from usuario.models import Usuario
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class UserForm(UserCreationForm):
	class Meta:
		model = User       
		fields = [
				'first_name',
				'last_name',
				'username',
				'email',
			]
		labels = {
				'first_name' : 'Nombre',
				'last_name' : 'Apellido',
				'username' : 'Nombre de usuario',
				'email' : 'Correo Electronico',
		}     

		help_texts = {
					'username' : None,
					'password2' : None,
					} 


'''
class UserProfileInfoForm(forms.ModelForm):
	class Meta:
		model = Usuario
		fields = ['proyecto']

		labels = {'proyecto' : 'Proyecto'}

		widget = {'proyecto' : forms.Select(attrs={'class':'form-control'})}
'''

ProyectoIS2/Proyecto/usuario/views.py
from django.shortcuts import render, redirect
from usuario.forms import UserForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.
def index_usuario(request):
	return render(request, "usuario/index.html")
'''
def usuario_create(request):
	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('usuario:listar_usuario')
	else:
		form = UserForm()
	return render(request, 'usuario/usuario_form.html', {'form':form})


def usuario_list(request):
	usuario = User.objects.all()
	contenido = {'usuarios':usuario}
	return render(request, 'usuario/listar_usuario.html', contenido)	
'''


class UsuarioList(ListView):
	model = User
	template_name = 'usuario/listar_usuario.html'

class UsuarioCreate(CreateView):
	model = User
	template_name = 'usuario/usuario_form.html'
	form_class = UserForm	
	success_url = reverse_lazy('usuario:listar_usuario')


class UsuarioUpdate(UpdateView):
	model = User
	form_class = UserForm
	template_name = 'usuario/usuario_form.html'
	success_url = reverse_lazy('usuario:listar_usuario')


class UsuarioDelete(DeleteView):
	model = User
	template_name = 'usuario/usuario_delete.html'
	success_url = reverse_lazy('usuario:listar_usuario')


def usuario_edit(request, id_usu):
	usuario = User.objects.get(id = id_usu)
	registered = False
	if request.method == 'GET' :
		form = UserForm(instance=usuario)
	else:
		form = UserForm(request.POST, instance=usuario)	
		if form.is_valid():
			form.save()
		return redirect('usuario:usuario_listar')
	return render(request,'usuario/usuario_form.html', {'form':form})

ProyectoIS2/Proyecto/templates/usuario/index.html
{% extends 'base/base.html'%}

ProyectoIS2/Proyecto/templates/usuario/listar_usuario.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-hover">
	<thead>
		<tr>
			<td align="center">N°</td>
			<td align="center">Nombre de Usuario</td>
			<td align="center">Nombre</td>
			<td align="center">Apellido</td>
			<td align="center">Correo Electronico</td>
			<td align="center">Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for usuario in object_list %}
		<tr class="table-dark">
			<td align="center">{{ usuario.id }}</td>
			<td align="center">{{ usuario.username }}</td>
			<td align="center">{{ usuario.first_name }}</td>
			<td align="center">{{ usuario.last_name }}</td>
			<td align="center">{{ usuario.email}}</td>
            <!--<td>{{ usuario.proyecto.nombre}}</td>-->
			<td align="center">
                <a class="btn btn-primary" href="{% url 'usuario:usuario_editar' usuario.id  %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'usuario:usuario_eliminar' usuario.id %}">Eliminar</a>
				<a class="btn btn-success" href="{% url 'proyecto:proyecto_listar' usuario.id %}">Ver Proyectos</a>
			</td>
		</tr>
		{% endfor %}
		<h2 align="center">Lista de Usuarios</h2>
		{% else %}
		<h2 align="center">No hay registros de Usuarios</h2>
		{% endif %}
	</tbody>
</table> 
            <h><a class="btn btn-success" href="{% url 'proyecto:index_proyecto' %}">Volver</a></h>

{% endblock%}

ProyectoIS2/Proyecto/templates/usuario/usuario_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar al usuario {{ object.username }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-success" href="{% url 'usuario:listar_usuario' %}">Cancelar</a>
</form>
{% endblock %}

ProyectoIS2/Proyecto/templates/usuario/usuario_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
</form>

	<!--<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="first_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Apellidos</label>
				<input class="form-control" type="text" name="last_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Nombre de usuario</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Correo</label>
				<input class="form-control" type="text" name="email">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Contraseña</label>
				<input class="form-control" type="password" name="password1">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Confirmar contraseña</label>
				<input class="form-control" type="password" name="password2">
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>-->
</form>
{% endblock %}