ProyectoIS2/Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from proyecto.views import index_proyecto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_portal, name='portal'),
    path('inicio/', include('home.urls')),
    path('logout/', views.user_logout, name='logout'), 
    path('inicio_proyecto/', index_proyecto, name='index'),
    path('proyecto/', include("proyecto.urls")),
    path('item/', include("item.urls")),
    path('usuario/', include("usuario.urls")),
    path('lineabase/', include("lineab.urls")), 
]

ProyectoIS2/Proyecto/home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns=[
	path('', views.index_portal, name='index'),
    path('',views.user_logout,name='logout'),
    path('ingresar/',views.user_login,name='user_login'),
  
]

ProyectoIS2/Proyecto/item/urls.py
from django.urls import path
from item.views import ItemCreate, ItemList, ItemUpdate, ItemDelete, item_list_total
app_name = 'item'

urlpatterns = [
    path("registrar/", ItemCreate.as_view(), name="registrar_item"),
    path("listar/<int:id>", ItemList.as_view(), name="listar_item"),   
    path('listaDeItem/', item_list_total, name= 'lista_total'),
    path("editar/<int:pk>", ItemUpdate.as_view(), name="editar_item"),   
    path("eliminar/<int:pk>", ItemDelete.as_view(), name="eliminar_item"),   

]

ProyectoIS2/Proyecto/lineab/urls.py
from django.urls import path
from lineab.views import LineaCreate, LineaList, LineaUpdate, LineaDelete, linea_list_total
app_name = 'lineab'

urlpatterns = [
    path("registrar/", LineaCreate.as_view(), name="registrar_linea"),
    path("listar/<int:id>", LineaList.as_view(), name="listar_linea"),   
    path('listaDeLineas/', linea_list_total, name= 'lista_total'),
    path("editar/<int:pk>", LineaUpdate.as_view(), name="editar_linea"),   
    path("eliminar/<int:pk>", LineaDelete.as_view(), name="eliminar_linea"),   

]

ProyectoIS2/Proyecto/proyecto/urls.py
from django.urls import path
from proyecto.views import index_proyecto, ProyectoCreate, ProyectoList, ProyectoUpdate, ProyectoDelete, proyecto_list_total

app_name = 'proyecto'

urlpatterns = [
    path("", index_proyecto, name="index_proyecto"),
    path("registrar/", ProyectoCreate.as_view(), name="registrar_proyecto"),
    path("listar/<int:id>", ProyectoList.as_view(), name="proyecto_listar"),
    path('listaDeProyecto/', proyecto_list_total, name= 'lista_total'),
    path("editar/<int:pk>", ProyectoUpdate.as_view(), name="editar_proyecto"),
    path("eliminar/<int:pk>", ProyectoDelete.as_view(), name="eliminar_proyecto"),
]

ProyectoIS2/Proyecto/lineab/models.py
from django.db import models
from  proyecto.models import Proyecto
# Create your models here.

class Linea_Base (models.Model):
	nombre_linea= models.CharField(max_length=300)
	HABILITADA = 'HAB'
	BLOQUEADA = 'BLO' 
	FINALIZADO = 'FIN'  
	tipo_estado = ((HABILITADA, 'Habilitada'),
				(BLOQUEADA, 'Bloqueada'),
				(FINALIZADO,'Finalizado'))
	estado =  models.CharField(max_length=15, choices = tipo_estado, default = HABILITADA)
	proyecto = models.ForeignKey(Proyecto, null=True, blank=True, on_delete=models.CASCADE)
	def __str__(self):	
		return self.nombre_linea

ProyectoIS2/Proyecto/lineab/forms.py
from django import forms
from lineab.models import Linea_Base

class LineaForm(forms.ModelForm):
	class Meta:
		model = Linea_Base
		fields = [
            'nombre_linea',
			'estado',
			'proyecto'
		]
		labels = {
            'nombre_linea':'Nombre de la Linea Base',
			'estado': 'Estado',
			'proyecto': 'Proyecto'
			
		}
		widgets = {
            'nombre_linea' : forms.TextInput(attrs={'class':'form-control'}),
			'estado' : forms.Select(attrs={'class':'form-control'}),
			'proyecto' : forms.Select(attrs={'class':'form-control'})
		}

ProyectoIS2/Proyecto/lineab/views.py
from django.shortcuts import render, redirect
from lineab.forms import LineaForm
from lineab.models import Linea_Base
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib import messages 
from django.contrib.messages.views import SuccessMessageMixin 
from django.urls import reverse
# Create your views here.
def linea_list_total(request):
	linea = Linea_Base.objects.all().order_by('id')
	contenido = {'lineas':linea}
	return render(request, 'lineab/listar_total_linea.html', contenido)


class LineaList(ListView):#Aca se agrega el filtro
	model = Linea_Base
	template_name = 'lineab/listar_linea.html'
	def get_queryset(self):
		return Linea_Base.objects.filter(proyecto=self.kwargs['id']).order_by('id')


class LineaCreate(CreateView):
	model = Linea_Base
	form_class = LineaForm
	template_name = 'lineab/linea_form.html'
	success_url = reverse_lazy('lineab:lista_total' )
	

class LineaUpdate(UpdateView):
	model = Linea_Base
	form_class = LineaForm
	template_name = 'lineab/linea_form.html'
	success_url = reverse_lazy('lineab:lista_total')


class LineaDelete(DeleteView):
	model = Linea_Base
	template_name = 'lineab/linea_delete.html'
	success_url = reverse_lazy('lineab:lista_total')

ProyectoIS2/Proyecto/templates/lineab/linea_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar la Linea Base {{ object.nombre_linea }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-success" href="{% url 'lineab:lista_total' %}">Cancelar</a>
</form>
{% endblock %}

ProyectoIS2/Proyecto/templates/lineab/linea_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
</form>
{% endblock %}

ProyectoIS2/Proyecto/templates/lineab/listar_linea.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-hover">
	<thead>
		<tr>
			<td align="center">N°</td>
			<td align="center"> Nombre </td>
			<td align="center">Estado</td>
			<td align="center">Proyecto</td>
			<td align="center">Acciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
			{% for lista in object_list %}
				<tr class="table-dark">
					<td align="center">{{ lista.id }}</td>
					<td align="center">{{ lista.nombre_linea }}</td>
					<td align="center">{{ lista.estado }}</td>
					<td align="center">{{ lista.proyecto.nombre }}</td>
					<td align="center">
						<a class="btn btn-primary" href="{% url 'lineab:editar_linea' lista.id %}">Editar</a>
						<a class="btn btn-danger" href="{% url 'lineab:eliminar_linea' lista.id %}">
							Eliminar
						</a>
						<a class="btn btn-success" href="{% url 'item:listar_item' lista.id %}">Ver Item</a>
					</td>
				</tr>
			{% endfor %}
			<h2 align="center">Lista de Linea Base</h2>	
		{% else %}
		<h2 align="center">No hay registros de Linea Base</h2>
		{% endif %}
	</tbody>
</table> 

<a class="btn btn-success" href="{% url 'proyecto:lista_total' %}">Volver</a>

{% endblock%}

ProyectoIS2/Proyecto/templates/lineab/listar_total_linea.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-hover">
	<thead>
		<tr>
			<td align="center">N°</td>
			<td align="center"> Nombre </td>
			<td align="center">Estado</td>
			<td align="center">Proyecto</td>
			<td align="center">Acciones</td>

		</tr>
		
	</thead>
	<tbody>
		{% if lineas %}
		{% for linea in lineas %}
		<tr class="table-dark">
			<td align="center">{{ linea.id }}</td>
			<td align="center">{{ linea.nombre_linea }}</td>
			<td align="center">{{ linea.estado }}</td>
			<td align="center">{{ linea.proyecto.nombre }}</td>
			<td align="center">
				<a class="btn btn-primary" href="{% url 'lineab:editar_linea' linea.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'lineab:eliminar_linea' linea.id %}">Eliminar</a>
				<a class="btn btn-success" href="{% url 'item:listar_item' linea.id %}">Ver Item</a>
			</td>
		</tr>
		{% endfor %}
			<h2 align="center">Lista de Linea Base</h2>	
		{% else %}
			<h2 align="center">No hay registros de Linea Base</h2>
		{% endif %}
	</tbody>
</table> 
	<h><a class="btn btn-success" href="{% url 'proyecto:index_proyecto' %}">Volver</a></h>
{% endblock%}